name: publish image to GitHub registry
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    name: publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Node environment for GitHub
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: publish to GitHub registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}